MCU = STM32F103
BOOTLOADER = stm32duino

LTO_ENABLE = yes
LEADER_ENABLE = yes
FAUXCLICKY_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
KEY_LOCK_ENABLE = no
TERMINAL_ENABLE = no
DEFERRED_EXEC_ENABLE = yes
ENCODER_MAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick